name: genassist_env
channels:
  - rocketce
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - alembic=1.15.2
  - amqp=5.2.0
  - annotated-types=0.6.0
  - anthropic=0.50.0
  - anyio=4.7.0
  - argcomplete=1.12.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asgiref=3.8.1
  - async-timeout=4.0.3
  - asyncpg=0.29.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.0
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.10.1
  - aws-c-io=0.19.0
  - aws-c-mqtt=0.13.0
  - aws-c-s3=0.7.17
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.5
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backoff=2.2.1
  - backports.zoneinfo=0.2.1
  - bcrypt=4.3.0
  - beautifulsoup4=4.12.3
  - billiard=4.2.1
  - blas=1.0
  - blinker=1.9.0
  - boto3=1.38.13
  - botocore=1.38.13
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cachetools=5.5.2
  - celery=5.4.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - chroma-hnswlib=0.7.6
  - chromadb=0.6.3
  - click=8.1.8
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.3.0
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - compressed-rtf=1.0.6
  - coverage=7.8.0
  - cpython=3.10.17
  - croniter=6.0.0
  - cryptography=44.0.3
  - cyrus-sasl=2.1.27
  - databases=0.9.0
  - datasets=2.14.4
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.3.7
  - distro=1.9.0
  - dnspython=2.7.0
  - docx2txt=0.9
  - ebcdic=1.1.1
  - ebooklib=0.17
  - ecdsa=0.19.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - fastapi-cli=0.0.7
  - filelock=3.18.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2025.3.2
  - future=0.18.3
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - googleapis-common-protos=1.70.0
  - greenlet=3.1.1
  - grpcio=1.71.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - httpx-sse=0.4.0
  - huggingface_hub=0.30.2
  - humanfriendly=10.0
  - icu=75.1
  - idna=3.7
  - imapclient=3.0.1
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_metadata=4.11.3
  - importlib_resources=6.5.2
  - inflect=7.0.0
  - jinja2=3.1.6
  - jiter=0.6.1
  - jmespath=1.0.1
  - joblib=1.5.0
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kombu=5.5.3
  - krb5=1.21.3
  - langchain=0.2.17
  - langchain-anthropic=0.1.23
  - langchain-chroma=0.2.2
  - langchain-core=0.2.43
  - langchain-huggingface=0.0.3
  - langchain-openai=0.1.25
  - langchain-text-splitters=0.2.4
  - langgraph=0.4.0
  - langgraph-checkpoint=2.0.21
  - langgraph-prebuilt=0.1.8
  - langgraph-sdk=0.1.66
  - langsmith=0.1.147
  - lark=1.1.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libarrow=20.0.0
  - libarrow-acero=20.0.0
  - libarrow-dataset=20.0.0
  - libarrow-substrait=20.0.0
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libcxx=20.1.4
  - libdeflate=1.23
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.4
  - libflac=1.5.0
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.71.0
  - libiconv=1.18
  - libintl=0.24.1
  - libjpeg-turbo=3.0.3
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libntlm=1.5
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopentelemetry-cpp=1.20.0
  - libopentelemetry-cpp-headers=1.20.0
  - libparquet=20.0.0
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.29.3
  - libpulsar=3.7.1
  - libre2-11=2024.07.02
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libxslt=1.1.41
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - loguru=0.7.3
  - lxml=5.3.0
  - lz4-c=1.10.0
  - mako=1.3.10
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mmh3=5.1.0
  - monotonic=1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msg-extractor=0.30.7
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nodejs=22.13.0
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - olefile=0.46
  - oletools=0.60
  - openai=1.77.0
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - orc=2.1.2
  - orjson=3.10.14
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - passlib=1.7.4
  - pdfminer.six=20250416
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pooch=1.8.2
  - posthog=4.0.1
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - psycopg2=2.9.10
  - pthread-stubs=0.3
  - pulsar-client=3.7.0
  - pyarrow=20.0.0
  - pyarrow-core=20.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.21
  - pycryptodome=3.21.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydantic-settings=2.9.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyopenssl=25.1.0
  - pyproject_hooks=1.2.0
  - pysocks=1.7.1
  - pytest=8.3.5
  - pytest-asyncio=0.26.0
  - python=3.10.17
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-flatbuffers=25.2.10
  - python-jose=3.3.0
  - python-kubernetes=32.0.1
  - python-multipart=0.0.20
  - python-pptx=1.0.2
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rich-toolkit=0.11.3
  - rsa=4.7.2
  - rtfde=0.1.2.1
  - s3transfer=0.12.0
  - safetensors=0.5.3
  - sentence-transformers=4.1.0
  - setuptools=78.1.1
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - speechrecognition=3.14.2
  - sqlacodegen=3.0.0
  - sqlalchemy=2.0.39
  - starlette-context=0.3.6
  - statsmodels=0.14.4
  - sympy=1.14.0
  - tenacity=8.5.0
  - text-generation=0.7.0
  - threadpoolctl=3.6.0
  - tiktoken=0.9.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tomli=2.2.1
  - tqdm=4.67.1
  - transformers=4.51.3
  - typer-slim=0.15.4
  - typer-slim-standard=0.15.4
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.2
  - urllib3=2.3.0
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - vine=5.1.0
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - websockets=10.4
  - wheel=0.45.1
  - wrapt=1.17.2
  - xlrd=2.0.1
  - xlsxwriter=3.2.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - anytree==2.13.0
      - ascii-colors==0.11.2
      - autograd==1.8.0
      - beartype==0.18.5
      - cfgv==3.4.0
      - configparser==7.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - distlib==0.3.9
      - durationpy==0.9
      - fastapi==0.115.9
      - fastapi-cache2==0.2.2
      - fonttools==4.57.0
      - gensim==4.3.3
      - google-auth==2.40.0
      - graspologic==3.4.1
      - graspologic-native==1.2.5
      - httptools==0.6.4
      - hyppo==0.4.0
      - identify==2.6.10
      - iniconfig==2.1.0
      - json-repair==0.39.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lightrag-hku==1.3.6
      - llvmlite==0.44.0
      - matplotlib==3.10.1
      - more-itertools==10.7.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - onnxruntime==1.21.1
      - openai-whisper==20240930
      - opentelemetry-api==1.32.1
      - opentelemetry-exporter-otlp-proto-common==1.32.1
      - opentelemetry-exporter-otlp-proto-grpc==1.32.1
      - opentelemetry-instrumentation==0.53b1
      - opentelemetry-instrumentation-asgi==0.53b1
      - opentelemetry-instrumentation-fastapi==0.53b1
      - opentelemetry-proto==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - opentelemetry-util-http==0.53b1
      - patsy==1.0.1
      - pendulum==3.1.0
      - pipmaster==0.7.2
      - pot==0.9.5
      - pre-commit==4.2.0
      - protobuf==5.29.4
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pypdf==5.4.0
      - pypika==0.48.9
      - pyuca==1.2
      - redis==6.0.0
      - referencing==0.36.2
      - rich==14.0.0
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.12.0
      - seaborn==0.13.2
      - smart-open==7.1.0
      - starlette==0.45.3
      - typer==0.15.3
      - types-pyyaml==6.0.12.20250402
      - umap-learn==0.5.7
      - uvloop==0.21.0
      - virtualenv==20.31.2
      - watchfiles==1.0.5
prefix: /opt/miniconda3/envs/genassist_env
